apiVersion: apps/v1
kind: Deployment
metadata:
  name: api2
  labels:
    app: api2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
      - name: api2
        image: gcr.io/the-programming-lab-379219/api2:latest
        ports:
        - containerPort: 8000
---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api2-backendconfig
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    healthyThreshold: 2
    type: HTTP
    requestPath: /api2/

---

apiVersion: v1
kind: Service
metadata:
  name: api2-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"api2-backendconfig"}}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: api2
