apiVersion: apps/v1
kind: Deployment
metadata:
  name: client3
  labels:
    app: client3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client3
  template:
    metadata:
      labels:
        app: client3
    spec:
      containers:
      - name: client3
        image: gcr.io/the-programming-lab-379219/client3:latest
        ports:
        - containerPort: 3000
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: client3-backendconfig
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    healthyThreshold: 2
    type: HTTP
    requestPath: /client3

---
apiVersion: v1
kind: Service
metadata:
  name: client3-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"client3-backendconfig"}}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: client3
