apiVersion: apps/v1
kind: Deployment
metadata:
  name: api3
  labels:
    app: api3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api3
  template:
    metadata:
      labels:
        app: api3
    spec:
      containers:
      - name: api3
        image: gcr.io/the-programming-lab-379219/api3:latest
        ports:
        - containerPort: 8000
---

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api3-backendconfig
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 300
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    unhealthyThreshold: 3
    healthyThreshold: 2
    type: HTTP
    requestPath: /api3/

---

apiVersion: v1
kind: Service
metadata:
  name: api3-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"api3-backendconfig"}}'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: api3
